/*********************************************************************************************
(c) 2005-2014 Copyright, Real-Time Innovations, Inc.  All rights reserved.
RTI grants Licensee a license to use, modify, compile, and create derivative works
of the Software.  Licensee has the right to distribute object form only for use with RTI
products.  The Software is provided "as is", with no warranty of any type, including
any warranty for fitness for any purpose. RTI is under no obligation to maintain or
support the Software.  RTI shall not be liable for any incidental or consequential
damages arising out of the use or inability to use the software.
**********************************************************************************************/

#ifndef RTIREFLEX_REFLEX_FWD_H
#define RTIREFLEX_REFLEX_FWD_H

struct DDS_DynamicData;

/**
 * @brief The top-level namespace for all the RefleX APIs.
 */
namespace reflex {

  class AutoDynamicData; // See auto_dd.h

  template <class T>
  class SafeDynamicData; // See safe_dynamidata.h 

  template <class T>
  class SafeTypeCode;   // See safe_typecode.h

  /**
  * @brief Creates a <a href="http://community.rti.com/rti-doc/510/ndds/doc/html/api_cpp/structDDS__TypeCode.html">TypeCode</a>
  *        for structured type T.
  * @param name Optional name for the top-level struct type.
  *        If none is provided, the unqualified name of type T is used.
  * @return The TypeCode for type T wrapped in a SafeTypeCode object.
  * @pre    Type T must be adapted using the RTI_ADAPT_STURCT macro.
  */
  template <class T>
  SafeTypeCode<T> make_typecode(const char * name = 0);

  /**
   * @brief Copies source data into the destination <a href="http://community.rti.com/rti-doc/510/ndds/doc/html/api_cpp/structDDS__DynamicData.html">
   *        DDS_DynamicData</a> instance.
   * @param src The source object
   * @param dest The DDS_DynamicData instance that will be populated
   * @return Nothing
   * @see reflex::make_typecode
   * @pre The TypeCode for the DDS_DynamicData instance must be generated by reflex::make_typecode.
   */
  template <class T>
  void write_dynamicdata(DDS_DynamicData &dest, const T & src);

  /**
  * @brief Copies source data into the destination <a href="http://community.rti.com/rti-doc/510/ndds/doc/html/api_cpp/structDDS__DynamicData.html">
  *        DDS_DynamicData</a> instance.
  * @param src The source object
  * @param dest The instance that will be populated
  * @return Nothing
  * @pre The TypeCode for the underlying DDS_DynamicData instance must be generated by reflex::make_typecode.
  */
  template <class T>
  void write_dynamicdata(AutoDynamicData &dest, const T & src);

  /**
   * @brief Extracts data out from the source <a href="http://community.rti.com/rti-doc/510/ndds/doc/html/api_cpp/structDDS__DynamicData.html">
   *        DDS_DynamicData</a> instance and copies into the destination object of type T.
   * @param src The source DDS_DynamicData.
   * @param dest The destination object of type T.
   * @see reflex::write_dynamicdata
   * @pre Type T must be adapted using the RTI_ADAPT_STURCT macro.
   */
  template <class T>
  void read_dynamicdata(T & dest, const DDS_DynamicData & src);

  /**
  * @brief Extracts data out from the AutoDynamicData instance and 
  *        copies into the destinatin object of type T.
  * @param src The source DDS_DynamicData.
  * @param dest The destination object of type T.
  * @see reflex::write_dynamicdata
  * @pre Type T must be adapted using the RTI_ADAPT_STURCT macro.
  */
  template <class T>
  void read_dynamicdata(T & dest, const AutoDynamicData & src);

  /**
  * Swap contents. Never throws.
  */
  //@{
  void swap(AutoDynamicData & lhs, AutoDynamicData & rhs) throw();

  template <class T>
  void swap(SafeDynamicData<T> & lhs, SafeDynamicData<T> & rhs) throw();

  template <class T>
  void swap(SafeTypeCode<T> & lhs, SafeTypeCode<T> & rhs) throw();
  //@}


  /**
  * @brief Contains types to adapt types of members 
  *        of structured type to an existing TypeCode.
  */
  namespace match {}

}



#endif // RTIREFLEX_REFLEX_FWD_H
