module darkart_gen {

  enum STATUS_FLAGS { 
    NORMAL = 0,
    ID_MISMATCH = 1,
    BAD_TIMESTAMP = 2
  };

  struct Baseline {
    boolean found_baseline;
    double  mean;
    double  variance;
  }; //@top-level false

  struct Channel {
    long    board_id; //@key
    long    channel_num;
    long    channel_id;
    string  label;
    long    trigger_count;
    long    sample_bits;
    double  sample_rate;
    long    trigger_index;
    long    nsamps;
    boolean saturated;
  };
};

